add methods for forestry ICharcoalManager
jaredlll08/ModTweaker pull request #678
Opened 2018-09-08 21:26 UTC by temp1011

There is a forge version and forestry version bump needed for this to work but I'm not sure what the best way to integrate that is. Specifically forge must be at least 14.23.4.2749 and forestry needs to be 5.8.1.341.

I'm not too experienced with writing stuff for zenscript so let me know if I've done anything wrong.

2018-09-09 07:47 UTC, kindlich requested changes
Most important of them all is the ZenClass name since this will prevent either your CharcoalPile or the Carpenter Handler from working!

2018-09-09 07:47 UTC, kindlich commented on src/main/java/com/blamejared/compat/forestry/CharcoalPile.java
> +@ZenClass("mods.forestry.Carpenter")
Carpenter -> Whatever name you see fit.

2018-09-09 07:47 UTC, kindlich commented on src/main/java/com/blamejared/compat/forestry/CharcoalPile.java
> +		private int amount;
If you're never changing it, you can make it final ^^

2018-09-09 07:47 UTC, kindlich commented on src/main/java/com/blamejared/compat/forestry/CharcoalPile.java
> +		protected static ICharcoalManager manager = TreeManager.charcoalManager;
If you never change them, make them final ^^
Also, try to instantiate them with at least the Null-reference to make Java happier ^^

2018-09-09 07:47 UTC, kindlich commented on src/main/java/com/blamejared/compat/forestry/CharcoalPile.java
> +		return (Block) internal;
You know that this will throw a ClassCastException if the condition for `logError` is met?
Why not return `null` in that instanceof Check?

2018-09-09 07:47 UTC, kindlich commented on src/main/java/com/blamejared/compat/forestry/CharcoalPile.java
> +		return (IBlockState) internal;
You know that this will throw a ClassCastException if the condition for `logError` is met?
Why not return `null` in that instanceof Check?

2018-09-09 13:38 UTC, temp1011 commented
Hopefully everything should be fixed up now. My initial code was definitely quite bad!

2018-09-09 14:24 UTC, kindlich commented
Looks good to me now.
Did you test your methods and if yes, care to provide an example script so that I have something to eventually add to the wiki?

2018-09-09 23:40 UTC, temp1011 commented
I used the small test added, it's not great but tests basic coverage. I'm happy to add more if needed.

2018-09-12 15:01 UTC, jaredlll08 commented
Can you add a method that takes an IItemStack and then converts that stack to a block, like the botania pure daisy

2018-10-19 12:16 UTC, merged